In [26]:
!pip install pandas
#!pip install difflib
import difflib

Requirement already satisfied: pandas in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (2.1.1)
Requirement already satisfied: numpy>=1.23.2 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from pandas) (1.26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [6]:
import pandas as pd

In [7]:
df=pd.read_csv("./action.csv")
df

,movie_id,movie_name,year,certificate,runtime,genre,rating,description,director,director_id,star,star_id,votes,gross(in $)
0,tt9114286,Black Panther: Wakanda Forever,2022,PG-13,161 min,"Action, Adventure, Drama",6.9,The people of Wakanda fight to protect their h...,Ryan Coogler,/name/nm3363032/,"Letitia Wright, \nLupita Nyong'o, \nDanai Guri...","/name/nm4004793/,/name/nm2143282/,/name/nm1775...",204835.0,NaN
1,tt1630029,Avatar: The Way of Water,2022,PG-13,192 min,"Action, Adventure, Fantasy",7.8,Jake Sully lives with his newfound family form...,James Cameron,/name/nm0000116/,"Sam Worthington, \nZoe Saldana, \nSigourney We...","/name/nm0941777/,/name/nm0757855/,/name/nm0000...",295119.0,NaN
2,tt5884796,Plane,2023,R,107 min,"Action, Thriller",6.5,A pilot finds himself caught in a war zone aft...,Jean-Fran√ßois Richet,/name/nm0724938/,"Gerard Butler, \nMike Colter, \nTony Goldwyn, ...","/name/nm0124930/,/name/nm1591496/,/name/nm0001...",26220.0,NaN
3,tt6710474,Everything Everywhere All at Once,2022,R,139 min,"Action, Adventure, Comedy",8.0,A middle-aged Chinese immigrant is swept up in...,"Dan Kwan, \nDaniel Scheinert",/name/nm3453283/,"Michelle Yeoh, \nStephanie Hsu, \nJamie Lee Cu...","/name/nm3215397/,/name/nm0000706/,/name/nm3513...",327858.0,NaN
4,tt5433140,Fast X,2023,NaN,NaN,"Action, Crime, Mystery",NaN,Dom Toretto and his family are targeted by the...,Louis Leterrier,/name/nm0504642/,"Vin Diesel, \nJordana Brewster, \nTyrese Gibso...","/name/nm0004874/,/name/nm0108287/,/name/nm0879...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52447,tt26743984,Suicide 2,1999,NaN,54 min,"Action, Drama, Horror",NaN,Matt awakens after trying to end his own life ...,"Brandon Womeldorff, \nMatt Brassfield",/name/nm13690776/,"Matt Hoffman, \nMatt Brassfield, \nBrandon Wom...","/name/nm1565857/,/name/nm7326486/,/name/nm1565...",NaN,NaN
52448,tt26744184,Chaos,2023,NaN,NaN,"Action, Thriller",NaN,Add a Plot,"Aditi Prabhudeva, \nSiddu Moolimani, \nAkshith...",/name/nm8898786/,NaN,"/name/nm7465869/,/name/nm12502668/,/name/nm545...",NaN,NaN
52449,tt26744484,Revolver Lily,NaN,NaN,NaN,"Action, Adventure",NaN,"Takes place in 1924 and centres on Yuri, who k...",Isao Yukisada,/name/nm0950834/,NaN,NaN,NaN,NaN
52450,tt26744765,The Wing,NaN,NaN,NaN,Action,NaN,The most secret and elite Special Forces unit ...,NaN,NaN,NaN,NaN,NaN,NaN
52451,tt26745202,Vey Dharuvey,NaN,NaN,NaN,"Action, Comedy",NaN,Add a Plot,D. Naveen Reddy,/name/nm14569102/,"Sunil, \nHebah Patel, \nKrishna Murali Posani,...","/name/nm1198628/,/name/nm6171293/,/name/nm0692...",NaN,NaN

In [8]:
dictionary = df ["movie_name"]
dictionary

0           Black Panther: Wakanda Forever
1                 Avatar: The Way of Water
2                                    Plane
3        Everything Everywhere All at Once
4                                   Fast X
                       ...
52447                            Suicide 2
52448                                Chaos
52449                        Revolver Lily
52450                             The Wing
52451                         Vey Dharuvey
Name: movie_name, Length: 52452, dtype: object

In [24]:
import difflib

# Define el vocabulario t√©cnico
vocabulario = dictionary.values
vocabulario = [str(item).lower() for item in vocabulario]

def encontrar_palabra_similar(palabra, vocabulario):
    sugerencia = difflib.get_close_matches(palabra, vocabulario, n=1, cutoff=0.6)

    if sugerencia:
        return sugerencia[0]
    else:
        return "No se encontr√≥ una palabra similar en el vocabulario"
while True: 
    # Ejemplo de uso
    palabra_usuario = input("Ingresa la palabra: ")  # La palabra tiene un error ortogr√°fico
    palabra_corregida = encontrar_palabra_similar(palabra_usuario, vocabulario)
    print(f"Palabra corregida: {palabra_corregida}")

Ingresa la palabra:  dharu

Palabra corregida: daru

KeyboardInterrupt: Interrupted by user